/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AssociationTypes {
  applies_to: string;
  description: string | null;
  id: string;
  inverse_id: string | null;
  is_directional: Generated<boolean>;
  is_system: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
}

export interface CatalogAliases {
  alias: string;
  created_at: Generated<Timestamp>;
  entry_id: string;
  id: string;
  normalized_alias: string;
  source: Generated<string>;
}

export interface CatalogEntries {
  attributes: Json | null;
  created_at: Generated<Timestamp>;
  id: string;
  is_verified: Generated<boolean>;
  name: string;
  type_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CatalogEntryAssociations {
  association_type_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  source_entry_id: string;
  target_entry_id: string;
}

export interface CatalogTypes {
  attribute_schema: Json | null;
  color: string | null;
  description: string | null;
  icon: string | null;
  id: string;
  is_system: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
}

export interface DocumentAgencies {
  agency_id: string;
  document_id: string;
}

export interface DocumentCatalogAssociations {
  association_type_id: string | null;
  context: string | null;
  created_at: Generated<Timestamp>;
  document_id: string;
  entry_id: string;
  id: string;
  role: string | null;
}

export interface DocumentCategories {
  description: string | null;
  id: string;
  max_government_entities: number | null;
  max_products: number | null;
  max_technologies: number | null;
  max_vendors: number | null;
  min_government_entities: number | null;
  min_products: number | null;
  min_technologies: number | null;
  min_vendors: number | null;
  name: string;
  require_government_location: boolean | null;
}

export interface DocumentDocumentAssociations {
  association_type_id: string;
  context: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  source_document_id: string;
  target_document_id: string;
}

export interface DocumentImportJobs {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  document_ids: Json | null;
  error_count: Generated<number>;
  error_details: Json | null;
  id: string;
  imported_count: Generated<number>;
  search_query: Json | null;
  skipped_count: Generated<number>;
  source_id: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  total_requested: number | null;
  user_id: string;
}

export interface DocumentMentions {
  confidence: Numeric | null;
  context_attributes: Json | null;
  created_at: Generated<Timestamp>;
  document_id: string;
  id: string;
  mentioned_name: string;
  normalized_name: string;
  resolved_at: Timestamp | null;
  resolved_entry_id: string | null;
  type_id: string;
}

export interface DocumentMetadata {
  confidence: Numeric | null;
  document_id: string;
  field_definition_id: string | null;
  field_key: string;
  id: string;
  source: Generated<string>;
  value_boolean: boolean | null;
  value_date: Timestamp | null;
  value_json: Json | null;
  value_number: Numeric | null;
  value_text: string | null;
}

export interface DocumentProcessingResults {
  ai_extracted_metadata: string | null;
  ai_extraction_completed_at: Timestamp | null;
  ai_extraction_error: string | null;
  ai_extraction_model: string | null;
  ai_extraction_performed: boolean | null;
  conversion_completed_at: Timestamp | null;
  conversion_performed: boolean | null;
  converted_filepath: string | null;
  document_id: string;
  original_mimetype: string | null;
  sieve_category: string | null;
  sieve_completed_at: Timestamp | null;
  sieve_confidence: Numeric | null;
  sieve_junk_score: Numeric | null;
  sieve_model: string | null;
  sieve_nexus_score: Numeric | null;
  sieve_performed: boolean | null;
  sieve_processing_time_ms: number | null;
  sieve_reasoning: string | null;
  virus_scan_completed_at: Timestamp | null;
  virus_scan_details: string | null;
  virus_scan_passed: boolean | null;
}

export interface Documents {
  category: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  document_date: Timestamp | null;
  external_id: string | null;
  filename: string;
  filepath: string;
  government_level: string | null;
  id: string;
  mimetype: string;
  place_geoid: string | null;
  processing_completed_at: Timestamp | null;
  processing_started_at: Timestamp | null;
  rejection_reason: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  size: Int8;
  source_id: string | null;
  state: Generated<string>;
  state_usps: string | null;
  title: string;
  tribe_id: string | null;
  updated_at: Generated<Timestamp>;
  uploader_id: string | null;
  use_ai_extraction: Generated<boolean>;
}

export interface DocumentSources {
  base_url: string;
  id: string;
  is_enabled: Generated<boolean>;
  name: string;
  rate_limit_per_day: number | null;
  rate_limit_per_second: number | null;
  requires_auth: Generated<boolean>;
}

export interface DocumentTags {
  created_at: Generated<Timestamp>;
  document_id: string;
  id: string;
  tag: string;
}

export interface JobExecutionLogs {
  completed_at: Timestamp | null;
  document_id: string | null;
  duration_ms: number | null;
  final_error: string | null;
  graphile_job_id: string;
  id: string;
  log_entries: Json | null;
  started_at: Timestamp;
  status: string;
  task_identifier: string;
}

export interface LlmCallLogs {
  completed_at: Timestamp | null;
  cost_cents: Numeric | null;
  document_id: string | null;
  error_code: string | null;
  error_message: string | null;
  id: string;
  input_tokens: number | null;
  job_id: string | null;
  model_id: string;
  output_tokens: number | null;
  processing_time_ms: number | null;
  response_summary: Json | null;
  started_at: Timestamp;
  status: string;
  task_type: string;
}

export interface MetadataFieldDefinitions {
  category_id: string;
  description: string | null;
  display_name: string;
  display_order: Generated<number>;
  enum_values: Json | null;
  field_key: string;
  id: string;
  is_ai_extractable: Generated<boolean>;
  is_required: Generated<boolean>;
  validation_rules: Json | null;
  value_type: string;
}

export interface Passkey {
  backedUp: boolean;
  counter: number;
  createdAt: Generated<Timestamp | null>;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
  webauthnUserID: string;
}

export interface Places {
  aland_sqmi: Numeric | null;
  funcstat: string | null;
  geoid: string;
  lat: Numeric;
  lon: Numeric;
  lsad: string | null;
  name: string;
  usps: string;
}

export interface PolicyTypes {
  description: string | null;
  id: string;
  name: string;
  sort_order: Generated<number>;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  version: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface StateAgencies {
  abbreviation: string | null;
  category: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  state_usps: string;
  updated_at: Generated<Timestamp>;
  website_url: string | null;
}

export interface StateMetadata {
  created_at: Generated<Timestamp>;
  id: string;
  key: string;
  state_usps: string;
  updated_at: Generated<Timestamp>;
  url: string | null;
  value: string;
}

export interface States {
  is_territory: Generated<boolean>;
  name: string;
  usps: string;
}

export interface TierLimits {
  id: string;
  limit_type: string;
  limit_value: number;
  tier_id: number;
}

export interface Tribes {
  created_at: Generated<Timestamp>;
  id: string;
  is_alaska_native: Generated<boolean>;
  name: string;
}

export interface TwoFactor {
  backupcodes: string;
  id: string;
  secret: string;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  role: Generated<string>;
  tier: Generated<number>;
  twoFactorEnabled: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
}

export interface UserApiCallLog {
  created_at: Generated<Timestamp>;
  id: string;
  limit_type: string;
  user_id: string;
}

export interface UserApiKeys {
  created_at: Generated<Timestamp>;
  daily_limit: Generated<number>;
  encrypted_key: string;
  id: string;
  key_hash: string;
  user_id: string;
}

export interface UserProfiles {
  place_geoid: string | null;
  state_usps: string | null;
  user_id: string;
}

export interface UserTiers {
  description: string | null;
  id: number;
  is_default: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
}

export interface Verification {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp | null>;
  value: string;
}

export interface DB {
  account: Account;
  association_types: AssociationTypes;
  catalog_aliases: CatalogAliases;
  catalog_entries: CatalogEntries;
  catalog_entry_associations: CatalogEntryAssociations;
  catalog_types: CatalogTypes;
  document_agencies: DocumentAgencies;
  document_catalog_associations: DocumentCatalogAssociations;
  document_categories: DocumentCategories;
  document_document_associations: DocumentDocumentAssociations;
  document_import_jobs: DocumentImportJobs;
  document_mentions: DocumentMentions;
  document_metadata: DocumentMetadata;
  document_processing_results: DocumentProcessingResults;
  document_sources: DocumentSources;
  document_tags: DocumentTags;
  documents: Documents;
  job_execution_logs: JobExecutionLogs;
  llm_call_logs: LlmCallLogs;
  metadata_field_definitions: MetadataFieldDefinitions;
  passkey: Passkey;
  places: Places;
  policy_types: PolicyTypes;
  schema_migrations: SchemaMigrations;
  session: Session;
  state_agencies: StateAgencies;
  state_metadata: StateMetadata;
  states: States;
  tier_limits: TierLimits;
  tribes: Tribes;
  two_factor: TwoFactor;
  user: User;
  user_api_call_log: UserApiCallLog;
  user_api_keys: UserApiKeys;
  user_profiles: UserProfiles;
  user_tiers: UserTiers;
  verification: Verification;
}
